name: Build docs and publish them to Github Pages

on:
  push:
    branches: ["nikkums/development"] # for now

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./docs/source/
